### PR TITLE
Implemented command for anonymizing and unanonymizing

### PR DESCRIPTION
**Pull request by parthr01**
Backend aspect
Implemented the anonymizing and "unanonymizing" posts via API commands in src/api/posts.js
Added assert commands to typecheck the parameters as 'objects'

### CODE REVIEW

**Review by TishyaaChaudhry — COMMENTED** [review]
Your changes look good, I think the tests are failing due to dependencies but this is good to be merged

**Review by TishyaaChaudhry — APPROVED** [review]
Approved

**Review by AlinaFang1123 — APPROVED** [review]
LGTM

**Review by arararz — APPROVED** [review]
Looks good

**Pull request merged**
